language: rust
rust:
  - stable
  - nightly

sudo: required
cache: cargo

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/shaneutt/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/keynome-*
